name: qixie
favicon: null
layout_spectrum: 0.00267
typography_spectrum: 0.2703753567766398
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#286bba'
    - '#6a6172'
    - '#2e3349'
    - '#010103'
    - '#7291c0'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
