name: qixie
favicon: null
layout_spectrum: 0.37181676365435123
typography_spectrum: 0.2703753567766398
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ff0000'
    - '#3c4d9f'
    - '#dbde6c'
    - '#ff43a9'
  brandStrength: 0.4375
  lightness: 0.375
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
